const problems = [
	'At the top, display "Calculator" in bold white text over a blue background, centered. Below this, arrange four rows of buttons (each containing three rectangular buttons with rounded corners, evenly spaced with gaps in between): Row 1: 1, 2, 3 (gray background, black text), Row 2: 4, 5, 6 (gray background, black text), Row 3: 7, 8, 9 (gray background, black text), Row 4: AC (red), 0 (gray), DEL (red). All buttons should be enclosed within a large square border. Below, add a "Send Number" button (red background, white text, full-width). At the bottom, include a text input field (full-width, gray background, black text, hint: "Enter here").', 

	'At the top, display "Weather Today" in bold black text over a yellow-orange gradient background. Below, place a search bar (gray background, black placeholder text "Enter City") with a magnifying glass icon on the right. Below this, display a large weather icon (sun, cloud, or rain) at the center with temperature in bold black text (e.g., "25°C"). Below, show a 5-day forecast with small weather icons and temperatures inside separate rectangular boxes with rounded corners, evenly spaced horizontally. At the bottom, add a "Refresh" button (blue background, white text, full-width).', 

	'At the top, display "Smart Home" in bold white text over a dark gray background. Below, place four large toggle switches labeled "Lights", "Fan", "AC", and "Heater" (gray when off, green when on) inside separate rectangular boxes with rounded corners. Below, add a slider (horizontal, blue track) to control brightness levels (0-100%). Below, include a "Set Temperature" input field (gray background, black text, hint: "Enter value in °C") with up and down buttons beside it. At the bottom, add a "Save Settings" button (blue background, white text, full-width).', 

	'At the top, display "Shop Now" in bold black text over a red background. Below, add a search bar (gray background, black text, search icon on the right). Below, display three product cards side by side, each containing: An image placeholder, Product name (bold black text), Price (red text), "Add to Cart" button (blue background, white text). Below, add a "View Cart" button (orange background, white text, full-width).', 

	'At the top, display "Profile" in bold black text over a blue gradient background. Below, add a circular profile picture placeholder in the center. Below, include three labeled input fields ("Name", "Bio", "Location") with white backgrounds and black text. Below, add three buttons: "Edit Profile" (blue), "View Posts" (gray), and "Logout" (red), all with white text. At the bottom, add a scrollable ListView to display posts with images, text, and timestamps.', 

	'At the top, display "My Bank" in bold black text over a dark green background. Below, show account balance in large bold text inside a gray rectangular box with rounded corners. Below, include four buttons ("Deposit", "Withdraw", "Transfer", "History") in a horizontal row, all blue with white text. Below, add a transaction history ListView with rows containing date, description, and amount (green for credit, red for debit).', 

	'At the top, display "Split The Bill" in bold white text over a purple background. Below, add four labeled input fields ("Total Amount", "Number of People", "Tip Percentage", "Custom Tip Amount") with light gray backgrounds and black text. Below these fields, add a toggle switch labeled "Enable Custom Tip" (gray when off, green when on). Below, add two buttons: "Split Equally" (blue background, white text) and "Split Unequally" (orange background, white text). Below, a table should display the split amounts, showing the amount per person in bold black text in separate rows. At the bottom, add a "Reset" button (red background, white text, full-width).', 

	'At the top, display "Workout Log" in bold white text over a dark green background. Below, add three drop-down menus ("Workout Type", "Duration", "Intensity") with gray backgrounds, black text, and a downward arrow icon on the right. Below them, add two input fields ("Workout Notes" and "Calories Target") with white backgrounds and gray borders. Below, add two toggle switches: "Outdoor Workout" (default: off) and "Enable Reminders" (default: off, green when on). Below, add a "➕ Add Workout" button (blue background, white text, full-width). Below this, a ListView should display the saved workouts, each entry showing the workout name (bold black text), duration (gray text), intensity (color-coded: green for Low, yellow for Medium, red for High), and calories target (italic gray text). On the right of each entry, add two buttons: "✏ Edit" (blue) and "❌ Delete" (red). At the bottom, add a progress bar (blue, full-width) to track weekly workout goals.', 

	'At the top, display "Smart Contact Manager" in bold white text over a navy blue background. Below, add three input fields ("Name", "Phone Number", "Email Address") with white backgrounds and gray borders. Below them, add a drop-down menu labeled "Category" (gray background, options: "Family", "Friends", "Work"). Below, add two buttons: "Save Contact" (green background, white text) and "Clear Fields" (red background, white text). Below this, a ListView should display contacts with profile picture placeholders, each row showing name (bold), phone number (gray), email (italic), and category color-coded (blue for Work, green for Family, yellow for Friends). On the right of each row, add two small buttons: "✏ Edit" (blue) and "❌ Delete" (red).', 

	'At the top, display "Digital Classroom" in bold white text over a dark blue background. Below, add a section labeled "Upcoming Classes" with a ListView showing subjects, timings, and a small calendar icon. Below, add three buttons ("Join Class", "View Notes", "Submit Homework") in a horizontal row, all green with white text. Below, add a discussion forum with a text input field (gray background, black text) and a "Post" button (blue background, white text).', 

	'At the top, display "Food Hub" in bold red text over a yellow-orange gradient background. Below, add a search bar (gray background, black text, search icon on the right). Below, display three food items in a row, each with an image, name, price, and "Add to Cart" button (green background, white text). Below, include a "Checkout" button (red background, white text, full-width).', 

	'At the top, display "Smart Task Manager" in bold white text over a dark blue gradient background. Below, add an input field (gray background, black text, hint: "Add a new task...") with a small "➕" button (blue background, white text) on the right. Below, add a section titled "Task Categories" with four category buttons ("Work", "Personal", "Shopping", "Urgent") arranged in a horizontal row (rounded edges, unique colors: Work - Blue, Personal - Green, Shopping - Yellow, Urgent - Red). Below, display a ListView containing tasks with checkboxes, task names, due dates (gray text), priority labels (color-coded: High - Red, Medium - Orange, Low - Green), and a delete button ("❌" in red).Below the task list, add a "Completed Tasks" section that collapses/expands when clicked. At the bottom, include two buttons: "Delete All Completed" (red background, white text, full-width) and "Export to PDF" (green background, white text, full-width).', 

	'At the top, display "Ride Now" in bold white text over a black background. Below, add two input fields ("Pickup Location", "Destination") with gray backgrounds, black text, and a small location icon on the right. Below, add three radio buttons ("Economy", "Standard", "Luxury") for ride type selection. Below, show a fare estimate in large bold text inside a yellow rectangular box with rounded corners. At the bottom, add two buttons: "Book Ride" (green background, white text) and "Cancel" (red background, white text, full-width).', 

	'At the top, display "Movie Booking" in bold black text over a dark red background. Below, include a dropdown menu for selecting a movie. Below, show a seat selection grid (6 rows, 10 seats per row) with empty seats in gray, selected seats in green, and occupied seats in red. Below, add a fare display in large bold text and two buttons: "Confirm Booking" (blue background, white text) and "Cancel" (red background, white text, full-width).', 

	'At the top, display "Habit Tracker" in bold white text over a dark green background. Below, add an input field (gray background, black text, hint: "Enter habit") with a "➕ Add" button (blue background, white text) on the right. Below, show a 7-day calendar row with each day in a small circular button (gray by default, green when habit is completed, red if skipped). Below, add a progress bar (blue track, updates based on habit completion) and two buttons: "View Stats" (blue background, white text) and "Reset Progress" (red background, white text).', 

	'At the top, display "Music Player" in bold black text over a dark purple gradient background. Below, show an album art image placeholder. Below, display song title (bold white text) and artist name (gray text). Below, add a horizontal progress bar (blue track, shows song progress) with a timer on the left (elapsed time) and right (total duration). Below, add three buttons: "⏮ Previous", "⏯ Play/Pause", and "⏭ Next" (gray background, white icons).', 

	'At the top, display "Quiz Time" in bold white text over a blue gradient background. Below, add a question in a large white text box with black text. Below, show four answer choices (each inside a gray rectangular button, black text, evenly spaced). Below, include a "Submit Answer" button (blue background, white text) and a score counter (white text, bold, inside a black rectangular box at the bottom right corner).', 

	'At the top, display "Expense Tracker" in bold black text over a dark green background. Below, add three input fields ("Amount", "Category", "Date") with gray backgrounds and black text. Below, include a "➕ Add Expense" button (blue background, white text). Below, display a ListView of expenses, each showing date, category, and amount (green for income, red for expenses). At the bottom, add a total balance display inside a bold black rectangular box with white text.', 

	'At the top, display "Fitness Tracker" in bold white text over a dark blue background. Below, add a step counter display in large white text inside a black rectangular box. Below, include three buttons: "Start Workout" (green), "Pause" (yellow), and "Stop" (red). Below, display a circular progress bar showing daily step goal completion (blue track).', 

	'At the top, display "Book Your Flight" in bold white text over a dark blue background. Below, add input fields for "From", "To", "Departure Date", and "Return Date" with gray backgrounds and black text. Below, include a dropdown for selecting flight class ("Economy", "Business", "First Class"). At the bottom, add two buttons: "Search Flights" (blue background, white text) and "Reset" (red background, white text).', 

	'At the top, display "User Dashboard" in bold black text on a yellow background, center-aligned. Below, arrange four rectangular boxes (equal width) in a 2x2 grid with a small icon on the left and a number (e.g., "254") on the right inside each box. Box 1 should have a blue background ("Total Orders"), Box 2 a green background ("Completed Orders"), Box 3 a red background ("Pending Orders"), and Box 4 a gray background ("Cancelled Orders"). Below this grid, display a pie chart-like structure using color-coded labels and a progress bar (blue, 70% filled) labeled "Performance".', 

	'At the top, display "Today\'s Headlines" in bold white text on a black background. Below, show a search bar (gray background, hint: "Search news…"). Below, list five news articles as separate horizontally-aligned cards with a title on the left and a thumbnail image on the right. Each card should have a red background for urgent news, a blue background for politics, and a green background for sports. At the bottom, add "View More" and "Refresh" buttons side by side, with black backgrounds and white text.', 

	'At the top, display "Smart Home" in bold black text on a dark blue background. Below, arrange four square icons in a 2x2 grid, each inside a gray bordered box. The first icon should be a lightbulb labeled "Lights", the second a fan labeled "Fan", the third a TV labeled "Television", and the fourth a lock labeled "Doors". Below, show a slider for "Brightness" (yellow track) and another for "Temperature" (blue track). At the bottom, display "All Devices OFF" and "All Devices ON" buttons (black background, white text).', 

	'At the top, display "Final Exam - Physics" in bold white text on a maroon background. Below, add a timer ("Time Left: 25:42") in a red rectangular box, center-aligned. Below, show a multiple-choice question ("What is Newton’s Second Law?") in black text inside a white box. Below, display four answer choices, each inside separate white bordered rectangles with radio buttons on the left. Below, add "Next Question" and "Previous Question" buttons (blue background, white text). At the bottom, show a progress indicator (e.g., "Question 5/20") as a horizontal bar, 25% filled in green.', 

	'At the top, display "John Doe | Marketing Expert" in bold black text over a gold gradient background. Below, show a circular profile picture in the center. Below, display four details ("Phone: 123-456-7890", "Email: john@example.com", "Company: XYZ Ltd.", "Website: www.johndoe.com") inside separate white bordered boxes with black text. At the bottom, add three social media buttons (Facebook, LinkedIn, Twitter) in a horizontal row with round blue, gray, and light blue backgrounds respectively.', 

	'At the top, display "Step 1: Personal Info" in bold white text on a blue background. Below, show two input fields ("Full Name", "Date of Birth") with gray backgrounds. Below, add a "Next Step" button (green background, white text) aligned to the right. At the bottom, display "Step 1/4" progress tracker as a thin blue progress bar (25% filled).', 

	'At the top, display "Choose Your Quiz" in bold black text on a dark green background. Below, show four category buttons ("Math", "Science", "History", "Geography") inside separate white-bordered boxes, evenly spaced in two rows. Below, display a "Start Quiz" button (blue background, white text) centered below the categories.', 

	'At the top, display "Delicious Bites" in bold white text on a dark brown background. Below, show a search bar (gray background, hint: "Search food…"). Below, display three sections ("Starters", "Main Course", "Desserts") as separate colored headers. Each section should contain two menu items with a thumbnail image on the left, name in bold black text, and price on the right. At the bottom, add "View Cart" and "Checkout" buttons (black background, white text) side by side.', 

	'At the top, display "Expense Tracker" in bold white text over a black background. Below, add a summary card with a green background displaying "Balance: $1,250". Below, list three recent transactions inside separate white-bordered boxes, with green text for income and red for expenses. At the bottom, add "Add Transaction" (blue background, white text) and "View Reports" (gray background, black text) buttons.', 

	'At the top, display "Your Fitness Journey" in bold white text on a blue gradient background. Below, show three vertical bars ("Steps", "Calories", "Workout Minutes") in red, blue, and green respectively, each partially filled. Below, display "Start Workout" (green background, white text) and "View Progress" (black background, white text) buttons side by side.', 

	'At the top, display "Checkout" in bold white text over a dark blue background. Below, show a summary box with "Total: $256.99" in bold black text on a yellow background. Below, add three input fields ("Name", "Shipping Address", "Phone Number") with gray backgrounds. Below, show two payment method buttons ("Credit Card", "PayPal") as side-by-side rounded boxes. At the bottom, add "Place Order" (red background, white text) and "Cancel" (gray background, black text) buttons side by side.', 

	'At the top, display "Book Your Trip" in bold black text on a teal gradient background. Below, add three input fields ("Destination", "Departure Date", "Return Date") with white backgrounds. Below, show two buttons ("Search Flights", "Search Hotels") side by side with blue and green backgrounds respectively. Below, display a "Trending Destinations" section with three rectangular image cards stacked vertically, each with an image on the left and a destination name on the right in bold black text.', 

	'At the top, display "My Courses" in bold black text on a dark orange background. Below, show a progress bar labeled "Completion Rate: 60%" (blue, 60% filled). Below, display three course cards ("Mathematics", "Science", "History") as horizontally-aligned rectangles, each with a small progress bar below it. Below, add "Continue Learning" (green background, white text) and "View All Courses" (gray background, black text) buttons side by side.', 

	'At the top, display "Upcoming Events" in bold black text over a light pink background. Below, show a list of three events, each inside a bordered rectangle with a small calendar icon on the left, event name in bold black text, and date on the right. Below, add "Register" (blue background, white text) and "View Details" (gray background, black text) buttons below each event.', 

	'At the top, display "Weather Forecast" in bold white text over a dark gray background. Below, show a search bar (gray background, hint: "Enter City Name"). Below, display a large weather card with a blue gradient background, showing "Temperature: 24°C" in bold white text, an icon of the sun, and "Partly Cloudy" in small black text. Below, add a horizontal row of small weather forecast boxes showing upcoming days (each with a date, temp, and icon).', 

	'At the top, display "Stock Market Overview" in bold black text on a dark green background. Below, show three stock prices inside separate white-bordered boxes with stock name, price, and percentage change (green for positive, red for negative). Below, display a large line chart (static image placeholder) with "Market Trends" label in bold black text above it. At the bottom, add "View Details" (blue background, white text) and "Refresh" (gray background, black text) buttons side by side.', 

	'At the top, display "Find Your Recipe" in bold black text over a dark red background. Below, show a search bar (gray background, hint: "Enter Ingredient…"). Below, display three vertically-stacked recipe cards, each with an image on the left, recipe name in bold black text, and a "View Recipe" button (yellow background, black text) on the right.', 

	'At the top, display "Meditation Timer" in bold black text over a light purple background. Below, show a circular timer (static placeholder) with "Time Left: 10:00" in bold black text inside. Below, add three buttons ("Start", "Pause", "Reset") side by side in green, red, and gray backgrounds respectively. At the bottom, add "Select Music" (blue background, white text) and "Set Duration" (gray background, black text) buttons side by side.', 

	'At the top, display "Shopping List" in bold black text over a yellow background. Below, show an input field (gray background, hint: "Enter item name…"). Below, display a vertically-stacked list of five grocery items inside separate white-bordered boxes, each with a checkbox on the left and a trash icon on the right. Below, add "Clear List" (red background, white text) and "Save List" (green background, white text) buttons side by side.', 

	'At the top, display "Book an Appointment" in bold black text over a dark blue background. Below, show three input fields ("Name", "Date", "Time") with white backgrounds. Below, display two buttons ("Confirm" in green, "Cancel" in red) side by side. At the bottom, add a small text label ("Upcoming Appointments:") with three listed appointments inside white-bordered boxes below it.'
];

export default problems;